name=M5Unit-CRYPTO
version=0.2.0
author=M5Stack
maintainer=M5Stack
sentence=Library for M5Stack UNIT CRYPTO using M5UnitUnified
paragraph=
category=Device Control
url=https://github.com/m5stack/M5Unit-CRYPTO
architectures=esp32
includes=M5UnitUnifiedCRYPTO.h
depends=M5UnitUnified,M5Utility,M5HAL
